# Secret with AWS credentials from .Values
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-aws-exporter-base.fullname" . }}-aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access_key_id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_access_key | b64enc | quote }}
  AWS_REGION: {{ .Values.aws.region | b64enc | quote }}

