{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "python-aws-exporter-base.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "python-aws-exporter-base.fullname" . }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.serviceMonitor.path }}
{{- end }}
