apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-aws-exporter-base.fullname" . }}
  labels:
    app: {{ include "python-aws-exporter-base.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "python-aws-exporter-base.fullname" . }}
